# Generated by Django 5.2.6 on 2025-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0005_admin_information_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_information',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
