# Generated by Django 5.2.6 on 2025-09-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0006_alter_admin_information_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital_department',
            name='name',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
