# Generated by Django 5.2.6 on 2025-10-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_user_id'),
        ('hospital_admin', '0007_hospital_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_specializations', to='hospital.hospital_information'),
        ),
    ]
