# Generated by Django 5.2.6 on 2025-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_information',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
