# Generated by Django 5.2.6 on 2025-11-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_hospital_information_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_application_source',
            field=models.CharField(blank=True, help_text='self = self registration, hospital = via hospital admin', max_length=16, null=True),
        ),
    ]
