# Generated by Django 5.2.6 on 2025-12-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_user_doctor_application_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor_application_source',
        ),
    ]
