# Generated by Django 5.2.6 on 2025-10-07 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_doctor_information_user_alter_testcart_id_and_more'),
        ('hospital', '0009_alter_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='doctor_information',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Hospital_Department',
            fields=[
                ('hospital_department_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_department_name', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_departments', to='hospital.hospital_information')),
            ],
        ),
    ]
