# Generated by Django 5.2.6 on 2025-10-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_specialization_and_more'),
        ('hospital', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='hospital.hospital_information'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
