# Generated by Django 5.2.6 on 2025-10-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_specialization_hospital_and_more'),
        ('hospital', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_certificate/'),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specializations', to='hospital.hospital_information'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization_name',
            field=models.CharField(max_length=200),
        ),
    ]
