# Generated by Django 5.2.6 on 2025-11-11 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_alter_doctor_information_hospital_name_and_more'),
        ('hospital', '0011_user_doctor_application_source'),
        ('hospital_admin', '0008_alter_specialization_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.hospital_department'),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='hospital_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information'),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_admin.specialization'),
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
