# Generated by Django 5.2.6 on 2025-11-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_alter_doctor_information_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
