# Generated by Django 5.2.6 on 2025-12-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0052_doctor_information_approval_status'),
        ('hospital', '0012_remove_user_doctor_application_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_information',
            name='approval_status',
        ),
        migrations.AlterField(
            model_name='doctor_information',
            name='hospital_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital_information'),
        ),
    ]
